<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<fmt:setTimeZone value="Asia/Kolkata"/>
<jsp:include page="common/header.jsp"><jsp:param name="pageTitle" value="Invoice"/></jsp:include>
<jsp:include page="common/sidebar.jsp"/>
<div class="container-fluid py-4">
 <div class="d-flex flex-wrap justify-content-between align-items-center mb-4">
  <div>
   <h1 class="page-title mb-1">Invoice ${invoice.invoiceNumber}</h1>
   <p class="text-muted mb-0">Created on <fmt:formatDate value="${invoice.createdAt}" pattern="dd MMM yyyy, hh:mm a"/></p>
  </div>
  <div class="d-flex gap-2 mt-2 mt-md-0">
   <button class="btn btn-outline-primary" onclick="window.print()"><i class="bi bi-printer me-1"></i>Print</button>
   <a href="${pageContext.request.contextPath}/invoices/pdf/${invoice.id}" class="btn btn-danger"><i class="bi bi-file-pdf me-1"></i>Download PDF</a>
   <a href="${pageContext.request.contextPath}/invoices/history" class="btn btn-secondary"><i class="bi bi-arrow-left me-1"></i>Back</a>
  </div>
 </div>

 <c:if test="${not empty success}"><div class="alert alert-success alert-dismissible fade show d-print-none"><i class="bi bi-check-circle me-2"></i>${success}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div></c:if>

 <div class="card dashboard-card invoice-card">
  <div class="card-body p-4">
   <!-- Invoice Header -->
   <div class="row mb-4">
    <div class="col-md-6">
     <h3 class="text-primary fw-bold"><i class="bi bi-receipt-cutoff me-2"></i>Smart Billing</h3>
     <p class="text-muted mb-0">Billing & Inventory Management System</p>
    </div>
    <div class="col-md-6 text-md-end">
     <h4 class="fw-bold">INVOICE</h4>
     <p class="mb-0"><strong>${invoice.invoiceNumber}</strong></p>
     <p class="text-muted mb-0"><fmt:formatDate value="${invoice.createdAt}" pattern="dd MMMM yyyy"/></p>
    </div>
   </div>
   <hr>
   <!-- Customer & Payment Info -->
   <div class="row mb-4">
    <div class="col-md-6">
     <h6 class="text-muted text-uppercase">Bill To</h6>
     <h5 class="fw-semibold">${invoice.customerName}</h5>
    </div>
    <div class="col-md-6 text-md-end">
     <h6 class="text-muted text-uppercase">Payment Method</h6>
     <span class="badge ${invoice.paymentType == 'Cash' ? 'bg-success' : 'bg-info'} fs-6">${invoice.paymentType}</span>
    </div>
   </div>
   <!-- Items Table -->
   <div class="table-responsive">
    <table class="table table-bordered mb-0">
     <thead class="table-dark"><tr><th>#</th><th>Product</th><th>Price</th><th>Qty</th><th>GST %</th><th>GST Amt</th><th>Total</th></tr></thead>
     <tbody>
      <c:forEach var="item" items="${invoice.items}" varStatus="s">
       <tr>
        <td>${s.index+1}</td>
        <td class="fw-semibold">${item.productName}</td>
        <td><fmt:formatNumber value="${item.price}" type="currency" currencySymbol="&#8377;"/></td>
        <td>${item.quantity}</td>
        <td>${item.gstPercentage}%</td>
        <td><fmt:formatNumber value="${item.gstAmount}" type="currency" currencySymbol="&#8377;"/></td>
        <td class="fw-semibold"><fmt:formatNumber value="${item.total}" type="currency" currencySymbol="&#8377;"/></td>
       </tr>
      </c:forEach>
     </tbody>
    </table>
   </div>
   <!-- Totals -->
   <div class="row mt-4">
    <div class="col-md-6"></div>
    <div class="col-md-6">
     <table class="table table-borderless">
      <tr><td class="text-end">Subtotal:</td><td class="text-end fw-semibold"><fmt:formatNumber value="${invoice.subtotal}" type="currency" currencySymbol="&#8377;"/></td></tr>
      <tr><td class="text-end">GST Amount:</td><td class="text-end fw-semibold"><fmt:formatNumber value="${invoice.gstAmount}" type="currency" currencySymbol="&#8377;"/></td></tr>
      <tr class="border-top"><td class="text-end fs-5 fw-bold">Grand Total:</td><td class="text-end fs-5 fw-bold text-success"><fmt:formatNumber value="${invoice.totalAmount}" type="currency" currencySymbol="&#8377;"/></td></tr>
     </table>
    </div>
   </div>
   <!-- Footer -->
   <div class="text-center mt-4 pt-4 border-top">
    <p class="text-muted mb-0">Thank you for your business!</p>
    <small class="text-muted">Generated by Smart Billing System</small>
   </div>
  </div>
 </div>
</div>
<jsp:include page="common/footer.jsp"/>
