name: Deploy Smart Billing

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build WAR
        run: mvn clean package -DskipTests

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Upload WAR
        run: |
          scp -i private_key.pem \
              -o StrictHostKeyChecking=no \
              target/smart-billing.war \
              ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/tmp/ROOT.war

      - name: Deploy
        run: |
          ssh -i private_key.pem \
              -o StrictHostKeyChecking=no \
              ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'

            sudo systemctl stop tomcat

            echo "Removing old deployment..."
            sudo rm -rf /opt/tomcat/webapps/ROOT
            sudo rm -f /opt/tomcat/webapps/ROOT.war

            echo "Clearing Tomcat cache..."
            sudo rm -rf /opt/tomcat/work/*
            sudo rm -rf /opt/tomcat/temp/*

            echo "Deploying new WAR..."
            sudo cp /tmp/ROOT.war /opt/tomcat/webapps/ROOT.war

            sudo chown tomcat:tomcat /opt/tomcat/webapps/ROOT.war

            echo "Starting Tomcat..."
            sudo systemctl start tomcat

            echo "Waiting for deployment..."
            sleep 15

          EOF
